github:
  is_project_page: false

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled:     true

theme: jekyll-theme-cayman

title: [HowAgile.org Resources]
description: []
show_downloads: false
google_analytics: UA-177167416-5
